# Schema for the configuration files of the arch module.

product.settings:
  type: config_object
  label: 'Product settings'
  mapping:
    use_admin_theme:
      type: boolean
      label: 'Use administration theme when editing or creating product'

arch_product.type.*:
  type: config_entity
  label: 'Product type'
  mapping:
    name:
      type: label
      label: 'Name'
    type:
      type: string
      label: 'Machine-readable name'
    description:
      type: text
      label: 'Description'
    help:
      type: text
      label: 'Explanation or submission guidelines'
    new_revision:
      type: boolean
      label: 'Whether a new revision should be created by default'
    preview_mode:
      type: integer
      label: 'Preview before submitting'

action.configuration.product_assign_owner_action:
  type: mapping
  label: 'Change the creator of content configuration'
  mapping:
    owner_uid:
      type: text
      label: 'Username'

action.configuration.product_unpromote_action:
  type: action_configuration_default
  label: 'Demote selected product from front page configuration'

action.configuration.product_promote_action:
  type: action_configuration_default
  label: 'Promote selected product from front page configuration'

action.configuration.product_delete_action:
  type: action_configuration_default
  label: 'Delete product configuration'

action.configuration.product_make_sticky_action:
  type: action_configuration_default
  label: 'Make selected product sticky configuration'

action.configuration.product_make_unsticky_action:
  type: action_configuration_default
  label: 'Make selected product unsticky configuration'

condition.plugin.product_type:
  type: condition.plugin
  mapping:
    bundles:
      type: sequence
      sequence:
        type: string
