group.type.*.third_party.subgroup:
  type: mapping
  label: 'Subgroup settings'
  mapping:
    depth:
      type: integer
      label: 'Depth'
    left:
      type: integer
      label: 'Left'
    right:
      type: integer
      label: 'Right'
    tree:
      type: string
      label: 'Tree ID'

subgroup.subgroup_role_inheritance.*:
  type: 'config_entity'
  label: 'Role inheritance'
  mapping:
    id:
      type: 'string'
      label: 'Machine-readable name'
    source:
      type: 'string'
      label: 'Source role ID'
    target:
      type: 'string'
      label: 'Target role ID'
    tree:
      type: 'string'
      label: 'Tree ID'
