rocketship_core.settings:
  type: config_object
  label: 'Rocketship Core settings'
  mapping:
    allow_header_paragraph_on_homepage:
      type: boolean
      label: 'Allow header paragraph on homepage'