<?php

/**
 * @file
 * Module file.
 */

/**
 * Implements hook_theme().
 */
function openfarm_footer_theme() {
  return [
    'openfarm_footer_mobile_footer_block' => [
      'variables' => [
        'follow' => NULL,
        'like' => NULL,
        'comment' => NULL,
        'share' => NULL,
        'main_class' => NULL,
        'cols' => NULL,
      ],
    ],
    'openfarm_powered_by' => [
      'variables' => [
        'links' => NULL,
        'logo' => NULL,
        'site_url' => NULL,
      ],
    ],
  ];
}
