<?php

use Drupal\Component\Render\FormattableMarkup;
use Drupal\Core\Datetime\DateFormatter;

/**
 * Implements hook_mail().
 */
function notification_system_dispatch_mail_mail($key, &$message, $params) {
  /** @var \Drupal\Core\Extension\ModuleHandlerInterface $moduleHandler */
  $moduleHandler = \Drupal::service('module_handler');

  /** @var DateFormatter $dateFormatter */
  $dateFormatter = \Drupal::service('date.formatter');

  /** @var \Drupal\Core\Template\TwigEnvironment $twig */
  $twig = \Drupal::service('twig');

  $langcode = $message['langcode'];

  $options = [
    'langcode' => $langcode,
  ];

  switch ($key) {
    case 'new_notification':
      $config = \Drupal::config('notification_system_dispatch_mail.settings');

      $message['from'] = \Drupal::config('system.site')->get('mail');

      $variables = [
        'notifications' => [],
      ];

      foreach($params['notifications'] as $notification) {
        $direct_link = $notification->getLink();
        if ($direct_link) {
          $direct_link = $direct_link->setAbsolute(TRUE)->toString();
        }

        $notificationVariables = [
          'title' => $notification->getTitle(),
          'body' => \Drupal\Core\Render\Markup::create($notification->getBody()),
          'timestamp' => $dateFormatter->format($notification->getTimestamp(), 'medium', '', NULL, $langcode),
          'link' => 'http://example.com',
          'direct_link' => $direct_link,
        ];

        $variables['notifications'][] = $notificationVariables;
      }

      $subjectTemplate = '{% spaceless %}' . $config->get('subject_template') . '{% endspaceless %}';
      $bodyTemplate = $config->get('body_template');

      $message['subject'] = $twig->renderInline($subjectTemplate, $variables);
      $message['body'][] = $twig->renderInline($bodyTemplate, $variables);


      // Support for swiftmailer module.
      if ($moduleHandler->moduleExists('swiftmailer')) {
        $message['headers']['Content-Type'] = SWIFTMAILER_FORMAT_HTML;
      }

      break;
  }
}
