name: feature_config
type: module
# core: 8.x
dependencies:
  - addtoany
  - block
  - block_content
  - ckeditor
  - comment
  - contact
  - ctools
  - editor
  - eform
  - entityform_block
  - feature_views
  - features
  - field
  - file
  - filter
  - help
  - image
  - instagram_block
  - menu_ui
  - node
  - owl
  - path
  - rdf
  - search
  - shortcut
  - simple_gmap
  - superfish
  - system
  - taxonomy
  - text
  - tour
  - user
  - views
  - views_ui

# Information added by Drupal.org packaging script on 2018-06-07
# version: '8.x-1.0-beta6+2-dev'
# core: '8.x'
# project: 'multipurpose_corporate_profile'
# datestamp: 1528358589

# Information added by Drupal.org packaging script on 2019-03-26
version: '8.x-1.2'
core: '8.x'
project: 'multipurpose_corporate_profile'
datestamp: 1553590327
