arch_payment_transfer.config:
  type: config_object
  label: 'Transfer Payment Configuration'
  mapping:
    complete_message:
      type: string
      label: 'Checkout Complete Message'
    business_name:
      type: string
      label: 'Business Name'
    account_number:
      type: string
      label: 'Bank Account Number'
    bank_provider:
      type: string
      label: 'Bank Provider'
    announcement:
      type: string
      label: 'Announcement'
    customer_bic:
      type: string
      label: 'BIC Number'
    customer_iban:
      type: string
      label: 'IBAN Number'
    currencies_variables:
      type: sequence
      label: 'Currencies variables'
      sequence:
        type: mapping
        label: 'Currency variables'
        mapping:
          business_name:
            type: string
            label: 'Business Name'
          account_number:
            type: string
            label: 'Bank Account Number'
          bank_provider:
            type: string
            label: 'Bank Provider'
          announcement:
            type: string
            label: 'Announcement'
          customer_bic:
            type: string
            label: 'BIC Number'
          customer_iban:
            type: string
            label: 'IBAN Number'
