<?php

/**
 * @file
 * Contains openfarm_holding.module.
 */

use Drupal\Core\Datetime\Element\Datetime;
use Drupal\Core\Datetime\Entity\DateFormat;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\node\NodeInterface;
use Drupal\openfarm_holding\Event\OpenfarmHoldingEvent;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_cron().
 */
function openfarm_holding_cron() {
  // Processing open/close scheduling holding nodes via cron.
  /** @var \Drupal\openfarm_holding\Service\OpenfarmHoldingService $holding_service */
  $holding_service = \Drupal::service('openfarm_holding.holding_service');
  $holding_service->openHoldings();
  $holding_service->closeHoldings();
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function openfarm_holding_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (isset($form['created']['widget'][0]['value'])) {
    $value = &$form['created']['widget'][0]['value'];
    $date_format = DateFormat::load('openfarm_date')->getPattern();
    $value['#description'] = t('<div>Note that scheduling is triggered using the server time.</div><div>Current server time is: %format.</div>', ['%format' => Datetime::formatExample($date_format)]);
    $form['#attached']['library'][] = 'openfarm_holding/openfarm_holding.schedule';
  }
}

/**
 * Implements hook_form_alter().
 */
function openfarm_holding_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (!in_array($form_id, ['node_holding_edit_form', 'node_holding_form'])) {
    return;
  }

  // Added visibility states to open_on and close_on form elements.
  $form['field_schedule_open']['#states'] = [
    'visible' => [
      ':input[name="field_is_open[value]"]' => ['checked' => FALSE],
    ],
  ];

  $form['field_schedule_close']['#states'] = [
    'visible' => [
      ':input[name="field_is_open[value]"]' => ['checked' => TRUE],
    ],
  ];

  // Move open_on/close_on form elements to the sidebar of the form.
  $form['holding_scheduling_options'] = [
    '#type' => 'details',
    '#description' => t('The schedule will be triggered by cron job and run every minute.'),
    '#title' => t('Holding Status'),
    '#group' => 'advanced',
  ];

  if (isset($form['field_schedule_open']['widget'][0]['value']['#attributes'])) {
    $form['field_schedule_open']['widget'][0]['value']['#attributes']['min'] = \Drupal::service('date.formatter')->format(\Drupal::time()->getRequestTime(), 'html_date');
  }
  if (isset($form['field_schedule_close']['widget'][0]['value']['#attributes'])) {
    $form['field_schedule_close']['widget'][0]['value']['#attributes']['min'] = \Drupal::service('date.formatter')->format(\Drupal::time()->getRequestTime(), 'html_date');
  }
  $form['holding_scheduling_options'][] = $form['field_is_open'];
  $form['holding_scheduling_options'][] = $form['field_schedule_open'];
  $form['holding_scheduling_options'][] = $form['field_schedule_close'];
  unset($form['field_is_open']);
  unset($form['field_schedule_open']);
  unset($form['field_schedule_close']);
}

/**
 * Implements hook_views_query_alter().
 */
function openfarm_holding_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  if ($view->id() === 'holdings' && $view->current_display === 'all_holdings_page' && $view->exposed_data['sort_by'] === 'field_schedule_close_value') {
    $table = 'node__field_schedule_close';
    $field = 'field_schedule_close_value';
    $alias = implode('_', [$table, $field, 'is_null']);

    // Add extra sort order to show holdings with empty "Closed On" field
    // value at the end.
    $query->addOrderBy(NULL, "ISNULL($table.$field)", 'ASC', $alias);
    $new_order_index = count($query->orderby) - 1;
    array_unshift($query->orderby, $query->orderby[$new_order_index]);
    unset($query->orderby[$new_order_index]);
  }
}

/**
 * Implements hook_entity_insert().
 */
function openfarm_holding_entity_insert(EntityInterface $entity) {
  if ($entity instanceof NodeInterface && $entity->bundle() == 'holding') {
    $event_dispatcher = \Drupal::service('event_dispatcher');
    $event = new OpenfarmHoldingEvent($entity);
    $event_dispatcher->dispatch($entity->field_is_open->value ? OpenfarmHoldingEvent::HOLDING_OPEN : OpenfarmHoldingEvent::HOLDING_CLOSE, $event);
  }
}

/**
 * Implements hook_entity_update().
 */
function openfarm_holding_entity_update(EntityInterface $entity) {
  if ($entity instanceof NodeInterface && $entity->bundle() == 'holding') {
    $event_dispatcher = \Drupal::service('event_dispatcher');
    // If holding was unpublished then don't
    // need to check schedule status.
    if (($entity->isPublished() && ($entity->original->isPublished() != $entity->isPublished()))
      || ($entity->original->get('field_is_open')->value != $entity->get('field_is_open')->value)) {
      $event = new OpenfarmHoldingEvent($entity);
      $event_dispatcher->dispatch($entity->get('field_is_open')->value ? OpenfarmHoldingEvent::HOLDING_OPEN : OpenfarmHoldingEvent::HOLDING_CLOSE, $event);
    }
  }
}
