arch_cart.config:
  type: config_object
  label: 'Cart Configuration'
  mapping:
    combine_items:
      type: boolean
      label: 'Combine same products within cart on add to cart event.'
    ajax_addtocart:
      type: boolean
      label: 'Enable or disable ajaxified Add to Cart form.'
