notification_system.settings:
  type: mapping
  label: 'Notification System settings'
  mapping:
    langcode:
      type: string
      label: 'Default language'
    group_mappings:
      type: sequence
      label: 'Group Mappings'
      sequence:
        type: mapping
        label: 'Group Mapping'
        mapping:
          notification_type:
            type: string
            label: 'Notification Type'
          notification_group:
            type: string
            label: 'Notification Group ID'
