notification_system.notification_group.*:
  type: config_entity
  label: 'Notification Group config'
  mapping:
    langcode:
      type: string
      label: 'Language code'
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    description:
      type: mapping
      label: 'Description'
      mapping:
        value:
          type: text
          label: 'Value'
        format:
          type: string
          label: 'Format'
    weight:
      type: integer
      label: 'Notification Group weight'
    uuid:
      type: string
