<?php

/**
 * @file
 * Contains openfarm_record.module.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Cache\RefinableCacheableDependencyInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Url;
use Drupal\node\NodeInterface;
use Drupal\openfarm_record\Plugin\Validation\Constraint\OpenfarmModerationStateConstraint;

/**
 * Implements hook_theme().
 */
function openfarm_record_theme() {
  return [
    'openfarm_record_flag_and_like_block' => [
      'variables' => [
        'like' => NULL,
        'follow' => NULL,
        'main_class' => NULL,
      ],
    ],
    'openfarm_record_info_block' => [
      'variables' => [
        'content' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_local_tasks_alter().
 */
function openfarm_record_local_tasks_alter(&$local_tasks) {
  $view = \Drupal::entityTypeManager()->getStorage('view')->load('moderated_content');
  if (isset($local_tasks['content_moderation.moderated_content']) && $view
    && ($display = $view->getDisplay('moderated_content'))
    && !$display['display_options']['enabled']) {
    unset($local_tasks['content_moderation.moderated_content']);
  }
}

/**
 * Implements hook_cron().
 */
function openfarm_record_cron() {
  $storage = \Drupal::entityTypeManager()->getStorage('node');
  // Node id.
  $entity_query = $storage->getQuery();

  $entities = $entity_query->condition('type', 'record')
    ->sort('changed', 'DESC')
    ->range(0, 50)
    ->execute();

  $records = $storage->loadMultiple($entities);
  /** @var \Drupal\node\NodeInterface $record */
  foreach ($records as $record) {
    $record->save();
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function openfarm_record_form_node_record_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Set default holding based on query parameter.
  if ($holding_id = \Drupal::request()->get('holding')) {
    if (isset($form['field_holding']['widget']['#options'][$holding_id])) {
      $form['field_holding']['widget']['#default_value'] = $holding_id;
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function openfarm_record_form_content_moderation_entity_moderation_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (isset($form['new_state'])) {
    $form['new_state']['#title_display'] = 'invisible';
    $form['new_state']['#prefix'] = '<span class="entity-moderation-form__item--state-title">' . $form['new_state']['#title'] . '</span>';
  }
  if (isset($form['revision_log'])) {
    $form['revision_log']['#access'] = FALSE;
  }
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function openfarm_record_node_presave(NodeInterface $node) {
  // Check entity type and duplicate_of field of the entity.
  if ($node->bundle() == 'record' && !$node->get('field_duplicate_of')->isEmpty()) {
    // Todo: Change the workflow state.
  }
  elseif ($node->bundle() == 'record') {
    $overall_score = \Drupal::service('openfarm_record.helper')->computeOverallScore($node->id());
    $node->set('field_overall_score', $overall_score);
  }
}

/**
 * Implements hook_entity_insert().
 */
function openfarm_record_entity_insert(EntityInterface $entity) {
  if ($entity->getEntityTypeId() == 'node' && $entity->bundle() == 'record') {
    try {
      // Create the group for the node.
      /** @var \Drupal\group\Entity\Group $group */
      $group = \Drupal::entityTypeManager()->getStorage('group')
        ->create([
          'label' => $entity->label(),
          'type' => 'record',
          'langcode' => 'en',
        ]);
      $group->save();

      // Need to add node to group before the member will be added
      // to be able fetch the node.
      //
      // Define the plugin id.
      $plugin_id = 'group_node:' . $entity->bundle();
      // Add the entity to the group.
      $group->addContent($entity, $plugin_id);

      // The group creator automatically becomes a member.
      $values = ['group_roles' => ['record-author']];
      $group->addMember($group->getOwner(), $values);

      // Author follow the node after its creating.
      /** @var \Drupal\flag\FlagService $flag_service */
      $flag_service = \Drupal::service('flag');
      $flag = $flag_service->getFlagById('follow');
      $flag_service->flag($flag, $entity, $entity->getOwner());
    }
    catch (Exception $e) {
      \Drupal::logger('openfarm_record')->error($e->getMessage());
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete().
 */
function openfarm_record_node_predelete(EntityInterface $entity) {
  if ($entity->bundle() == 'record') {
    // Delete the group that contains this node.
    if ($group = _openfarm_record_get_group_by_entity($entity)) {
      $group->delete();
    }
  }
}

/**
 * Implements hook_entity_access().
 */
function openfarm_record_entity_access(EntityInterface $entity, $operation, AccountInterface $account) {
  if ($entity->getEntityTypeId() === 'comment') {
    $commented_entity = $entity->getCommentedEntity();
    if ($commented_entity->bundle() === 'record' && $operation === 'update') {
      return AccessResult::forbiddenIf(!$commented_entity->get('field_duplicate_of')->isEmpty());
    }
  }

  // @Todo: Remove once appropriate permissions will be implemented
  // https://www.drupal.org/project/drupal/issues/2808309
  $moderation_info = Drupal::service('content_moderation.moderation_information');
  if ($operation === 'update' && $moderation_info->isModeratedEntity($entity) && $entity->moderation_state && $entity instanceof NodeInterface) {
    // Get the group member.
    $helper = \Drupal::service('openfarm_record.helper');
    $member = $helper->getGroupMember($account, $entity);
    if ($member && $member->hasPermission('update own group_node:record entity')) {
      return AccessResult::neutral();
    }
    return content_moderation_entity_access($entity, $operation, $account);
  }
}

/**
 * Implements hook_ENTITY_TYPE_create_access().
 */
function openfarm_record_comment_create_access(AccountInterface $account, array $context, $entity_bundle) {
  /** @var \Drupal\node\NodeInterface $node */
  $node = \Drupal::routeMatch()->getParameter('node');
  if ($node instanceof NodeInterface && $node->bundle() === 'record') {
    return AccessResult::forbiddenIf(!$node->get('field_duplicate_of')->isEmpty());
  }
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function openfarm_record_menu_local_tasks_alter(&$data, $route_name, RefinableCacheableDependencyInterface &$cacheability) {
  if ($route_name !== 'entity.node.canonical') {
    return;
  }

  $node = \Drupal::routeMatch()->getParameter('node');
  if ($node->bundle() === 'record' && $group = _openfarm_record_get_group_by_entity($node)) {
    $data['tabs'][0]['group.members'] = [
      '#theme' => 'menu_local_task',
      '#link' => [
        'title' => t('Members'),
        'url' => Url::fromRoute('view.group_members.page_1', ['group' => $group->id()]),
        'localized_options' => [],
      ],
      '#access' => $group->hasPermission('view group_membership content', \Drupal::currentUser()),
    ];

    // The tab we're adding is dependent on a user's access to add content.
    $cacheability->addCacheContexts(['user.group_permissions']);
  }
}

/**
 * Get single group entity that represents a given entity.
 *
 * @param object $entity
 *   Entity instance.
 *
 * @return \Drupal\group\Entity\GroupInterface|null
 *   Group entity or NULL.
 */
function _openfarm_record_get_group_by_entity($entity) {
  // In our case we will have one node per group.
  // We get all group ids but return just the first one.
  $group_contents = \Drupal::entityTypeManager()
    ->getStorage('group_content')
    ->loadByEntity($entity);
  foreach ($group_contents as $group_content) {
    $groups[] = $group_content->getGroup();
  }

  return !empty($groups) ? array_shift($groups) : NULL;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function openfarm_record_form_views_exposed_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form['#id'] != 'views-exposed-form-records-all-records-page') {
    return;
  }
  // Remove workflow title form the views exposed filter.
  // @see https://www.drupal.org/project/drupal/issues/3091182
  if (isset($form['phase']['#options']['Life Cycle Phases'])) {
    foreach ($form['phase']['#options']['Life Cycle Phases'] as $key => $phase_option) {
      $form['phase']['#options'][$key] = $phase_option;
    }
    unset($form['phase']['#options']['Life Cycle Phases']);
  }
  // Get the list of published and opened holdings.
  $node_storage = \Drupal::entityTypeManager()->getStorage('node');
  $query = $node_storage->getQuery()
    ->condition('type', 'holding', '=')
    ->condition('field_is_open', TRUE, '=')
    ->condition('status', NodeInterface::PUBLISHED)
    ->latestRevision()
    ->sort('title');
  $nids = $query->execute();

  if (empty($nids)) {
    $form['holding']['#access'] = FALSE;
    return;
  }

  /** @var \Drupal\node\NodeInterface $node */
  $options = [];
  foreach ($node_storage->loadMultiple($nids) as $node) {
    $options[$node->id()] = $node->getTitle();
  }
  // Replace existing holding form element with select.
  $form['holding'] = [
    '#type' => 'select',
    '#multiple' => FALSE,
    '#empty_option' => t("Any"),
    '#options' => $options,
  ];
}

/**
 * Implements hook_ENTITY_TYPE_access().
 */
function openfarm_record_group_content_access(EntityInterface $entity, $operation, AccountInterface $account) {
  if ($entity->getOwnerId() === $account->id()
    && $operation == 'delete'
    && $entity->getContentPlugin()->getPluginId() == 'group_membership') {
    return AccessResult::forbidden();
  }

  return AccessResult::neutral();
}

/**
 * Implements hook_rrssb_buttons_alter().
 */
function openfarm_record_rrssb_buttons_alter(&$buttons) {
  $theme = \Drupal::service('theme_handler')->getTheme('openfarm_theme');
  $theme_path = $theme->getPath();
  $buttons['facebook']['svg'] = $theme_path . '/images/icons/facebook.svg';
  $buttons['copy_url']['svg'] = $theme_path . '/images/icons/clipboard.svg';
  $buttons['twitter']['svg'] = $theme_path . '/images/icons/twitter.svg';
  $buttons['linkedin']['svg'] = $theme_path . '/images/icons/linkedin.svg';
}

/**
 * Implements hook_rrssb_buttons().
 */
function openfarm_record_rrssb_buttons() {
  return [
    'copy_url' => [
      'share_url' => '',
      'color' => '',
      'color_hover' => '',
    ],
  ];
}

/**
 * Implements hook_module_implements_alter().
 */
function openfarm_record_module_implements_alter(&$implementations, $hook) {
  // Remove content moderation implementation of hook_entity_access.
  // If the user has not permission to update the content moderation,
  // if not allow to edit whole node, but we need to have the ability to.
  // @See: openfarm_record_entity_access()
  // @Todo: Remove once appropriate permissions will be implemented
  // https://www.drupal.org/project/drupal/issues/2808309
  if ($hook == 'entity_access' && isset($implementations['content_moderation'])) {
    unset($implementations['content_moderation']);
  }
}

/**
 * Implements hook_validation_constraint_alter().
 */
function openfarm_record_validation_constraint_alter(array &$definitions) {
  $definitions['ModerationState']['class'] = OpenfarmModerationStateConstraint::class;
}
