
field.formatter.settings.product_group_default:
  type: mapping
  label: 'Product Group ID default display format settings'
  mapping:
    view_mode:
      type: string
      label: 'Group item display view mode'

field.formatter.settings.product_matrix:
  type: mapping
  label: 'Product Group ID product matrix display format settings'
  mapping:
    ajax:
      type: boolean
      label: 'Update page with AJAX'
    fields:
      type: sequence
      label: 'Matrix fields'
      sequence:
        type: string
