commerce_ticketing.commerce_ticket_type.*:
  type: config_entity
  label: 'Commerce Ticket type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
