name: 'Configuration Single Export'
type: module
description: 'Adds an Export button to single configuration export form enabling administrators to export single settings with one click.'
package: Development
# version: 8.x-1.0-dev
core: 8.x
core_version_requirement: ^8 || ^9
dependencies:
  - drupal:config
tags:
  - developer:developer

# Information added by Drupal.org packaging script on 2020-12-10
version: '8.x-1.3'
project: 'config_single_export'
datestamp: 1607596963
