<?php

/**
 * @file
 * Hooks and customizations for the log module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function log_help($route_name, RouteMatchInterface $route_match) {
  $output = '';

  // Main module help for the log module.
  if ($route_name == 'help.page.log') {
    $output = '';
    $output .= '<h3>' . t('About') . '</h3>';
    $output .= '<p>' . t('Provides Log entity') . '</p>';
  }

  return $output;
}
