resources.type.*:
  type: config_entity
  label: 'Resources type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    display:
      type: boolean
      label: 'Display'
    uuid:
      type: string
